### ISSUE TITLE
Editor is blocked by the top bar when input method is activated

### ISSUE THREAD

**Issue by bigshans** [Daniele-rolli/Beaver-notes-pocket#3]
**Describe the bug**
The editor is blocked by the top bar when the input method is activated

**To Reproduce**
1. Click the add button.
2. Enter the editing page.
3. Click “Write something”.

**Expected behavior**
The top bar shouldn't block the editor.

**Screenshots**
![图片](https://github.com/Daniele-rolli/Beaver-notes-pocket/assets/26884666/ed01599d-1443-4c5b-bff9-f63a3fdbae80)

**Smartphone**
 - OS: Android 14 (emulator)
 - Browser: in the application

**Additional context**

**Comment by Daniele-rolli** [comment]
Noted, I'll make sure to reduce the padding.
